[package]
name = "try-polyfill-macro"
version = "0.1.0"
edition = "2021"
msrv = "1.65.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit-mut"] }
proc-macro2 = "1.0"
rand = "0.8"
